### PR TITLE
Cohere to gulp plugin guidelines

### PR DESCRIPTION
**Pull request by stnvh**
Currently, this writes the file to disk to read :-1: 

It's good practice to keep everything in the stream, and speeds things up, too!

### CODE REVIEW

**Comment by furzeface** [comment]
Thanks, I'll merge this in later and do a new release!

**Comment by JimmyMultani** [comment]
Hey @furzeface, will this be merged soon? Thanks.

**Comment by furzeface** [comment]
Will npm publish when I have time. Ping me in a week if I haven't been able to yet.

**Comment by furzeface** [comment]
Thank you @stnvh by the way, seems like it'll be a great help. :smile:

**Comment by stnvh** [comment]
@furzeface any updates on publish progress?

**Pull request merged**
